# Generated by Django 4.1 on 2024-03-19 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
                ('daytime', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('booked_slots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('package', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=255)),
                ('plan', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default=None, max_length=7, null=True)),
                ('start_date', models.DateField(default=datetime.date(2024, 3, 21), null=True)),
                ('end_date', models.DateField(null=True)),
                ('type_of_call', models.CharField(choices=[('COURTESY_CALLS', 'Courtesy Calls'), ('WELLNESS_CALLS', 'Wellness Calls'), ('PHONE_A_FRIEND', 'Phone A Friend'), ('MEDICATION_MEDICAL_REMINDER', 'Medication Medical Reminder'), ('MEMORIAL_MESSAGE_TRIBUTE', 'Memorial Message Tribute'), ('MEAL_REMINDER_CALL', 'Meal Reminder Call')], max_length=255)),
                ('mode_of_call', models.CharField(choices=[('TEXT', 'Text'), ('VOICE_CALL', 'Voice Call')], max_length=255)),
                ('response_mail', models.EmailField(max_length=254)),
                ('alternate_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ON HOLD', 'ON HOLD'), ('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('CANCELED', 'CANCELED')], default='ON HOLD', max_length=255)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateField(default=datetime.date.today, null=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionScheduleText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_status_id', models.IntegerField()),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=255)),
                ('daytime', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionScheduleCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('agent_user_id', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('avaialbleslote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.availableslots')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.JSONField(default=list)),
                ('session', models.JSONField(default=list)),
                ('time', models.JSONField(default=list)),
                ('booked', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('MISSED', 'Missed'), ('ATTENDED', 'Attended'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('callschedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionschedulecall')),
                ('textschedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionscheduletext')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_confirmation', models.CharField(max_length=225)),
                ('payment_indent_id', models.CharField(max_length=512)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
    ]
