# Generated by Django 4.1 on 2024-03-20 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 22), null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type_of_call',
            field=models.CharField(choices=[('COURTESY_CALLS', 'COURTESY_CALLS'), ('WELLNESS_CALLS', 'WELLNESS_CALLS'), ('PHONE_A_FRIEND', 'PHONE_A_FRIEND'), ('MEDICATION_MEDICAL_REMINDER', 'MEDICATION_MEDICAL_REMINDER'), ('MEMORIAL_MESSAGE_TRIBUTE', 'MEMORIAL_MESSAGE_TRIBUTE'), ('MEAL_REMINDER_VOICE', 'MEAL_REMINDER_VOICE')], max_length=255),
        ),
    ]
