# Generated by Django 4.1 on 2024-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_trialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialstatus',
            name='alternate_contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
