# Generated by Django 4.1 on 2024-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_trialstatus_alternate_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='mode_of_call',
            field=models.CharField(choices=[('SMS', 'SMS'), ('VOICE', 'VOICE')], max_length=255),
        ),
    ]
