# Generated by Django 4.1 on 2024-03-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionschedulecall',
            name='id',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionscheduletext',
            name='id',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
