# Generated by Django 4.1 on 2024-03-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_alter_subscriptionschedulecall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 24), null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type_of_call',
            field=models.CharField(choices=[('COURTESY CALLS', 'COURTESY_CALLS'), ('WELLNESS_CALLS', 'WELLNESS_CALLS'), ('PHONE A FRIEND', 'PHONE_A_FRIEND'), ('MEDICATION_REMINDERS_CALL', 'MEDICATION_REMINDERS_CALL'), ('MEMORIAL_MESSAGE_TRIBUTE', 'MEMORIAL_MESSAGE_TRIBUTE'), ('MEAL_REMINDER_CALL', 'MEAL_REMINDER_CALL')], max_length=255),
        ),
    ]
