# Generated by Django 4.1 on 2024-03-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_alter_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type_of_call',
            field=models.CharField(choices=[('COURTESY_CALLS', 'COURTESY_CALLS'), ('WELLNESS_CALLS', 'WELLNESS_CALLS'), ('PHONE_A_FRIEND', 'PHONE_A_FRIEND'), ('MEDICATION_REMINDERS_CALL', 'MEDICATION_REMINDERS_CALL'), ('MEMORIAL_MESSAGE_TRIBUTE', 'MEMORIAL_MESSAGE_TRIBUTE'), ('MEAL_REMINDER_CALL', 'MEAL_REMINDER_CALL')], max_length=255),
        ),
    ]
