# Generated by Django 4.1 on 2024-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_subscription_type_of_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialstatus',
            name='alternate_contact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trialstatus',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
