# Generated by Django 4.1 on 2024-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_trialstatus_alternate_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ON HOLD', 'ON HOLD'), ('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='ON HOLD', max_length=255),
        ),
    ]
