# Generated by Django 4.1 on 2024-03-26 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestatus',
            name='callschedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='subscription.subscriptionschedulecall'),
        ),
        migrations.AlterField(
            model_name='schedulestatus',
            name='textschedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_status', to='subscription.subscriptionscheduletext'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 28), null=True),
        ),
    ]
