# Generated by Django 4.1 on 2024-04-02 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_alter_schedulestatus_callschedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 4), null=True),
        ),
    ]
