# Generated by Django 4.1 on 2024-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type_of_call',
            field=models.CharField(choices=[('COURTESY_CALLS', 'COURTESY_CALLS'), ('WELLNESS_CALLS', 'WELLNESS_CALLS'), ('PHONE_A_FRIEND', 'PHONE_A_FRIEND'), ('MEDICATION_REMINDERS_CALL', 'MEDICATION_REMINDERS_CALL'), ('MEAL_REMINDER_CALL', 'MEAL_REMINDER_CALL')], max_length=255),
        ),
    ]
