# Generated by Django 4.1 on 2024-04-08 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_alter_subscription_type_of_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestatus',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MISSED', 'Missed'), ('VOICE_MAIL', 'Voice Mail'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 10), null=True),
        ),
    ]
