# Generated by Django 4.1 on 2024-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
