# Generated by Django 4.1 on 2024-04-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_slots_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialStatus',
        ),
    ]
