# Generated by Django 4.1 on 2024-04-25 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0025_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 27), null=True),
        ),
    ]
