# Generated by Django 4.1 on 2024-04-26 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0026_alter_subscription_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='response_mail',
            new_name='communication_email',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 28), null=True),
        ),
    ]
