# Generated by Django 4.1 on 2024-05-16 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0028_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 18), null=True),
        ),
    ]
