name: subscription model

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get install -y openssh-client

    - name: Remove offending ECDSA key
      run: ssh-keygen -R "${{ secrets.EC2_HOST }}"

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
      
    - name: Deploy to EC2
      run: |
        set -e
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh_key.pem
        chmod 600 ssh_key.pem  # Ensure appropriate permissions
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
        cd /var/www/Backend-form
        sudo git pull
        cd src
        docker-compose build
        docker-compose -f docker-compose.yaml up -d
        ENDSSH
      shell: bash
